spring:
  datasource:
    dynamic:
      primary: mybatis #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        mybatis:
          url: jdbc:mysql://hadoop102:3306/dga?useSSL=false&useUnicode=true&characterEncoding=UTF-8
          username: root
          password: "000000"
          driver-class-name: com.mysql.cj.jdbc.Driver
          druid:
            initial-size: 5
            max-active: 20
            max-wait: 60000
            min-idle: 5
            test-on-borrow: true
            test-on-return: false
            test-while-idle: true
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure

#前缀全部替换为mybatis-plus
mybatis-plus:
  mapper-locations: classpath*:/mappers/*Mapper.xml
  configuration:
    mapUnderscoreToCamelCase: true


#日志级别从低到高: trace debug info warn error fatal
logging:
  level:
    com:
      atguigu:
        dga:
          meta:
            mapper: debug
